// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlDbAnalyze.Repository.Contexts;

#nullable disable

namespace SqlDbAnalyze.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SqlDbAnalyze.Repository.Entities.CachedDtuMetricEntity", b =>
                {
                    b.Property<long>("CachedDtuMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("DtuPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("RegisteredServerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("CachedDtuMetricId");

                    b.HasIndex("RegisteredServerId")
                        .HasDatabaseName("IX_CachedDtuMetric_RegisteredServerId");

                    b.HasIndex("RegisteredServerId", "DatabaseName", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("UQ_CachedDtuMetric_Server_Database_Timestamp");

                    b.ToTable("CachedDtuMetric", (string)null);
                });

            modelBuilder.Entity("SqlDbAnalyze.Repository.Entities.RegisteredServerEntity", b =>
                {
                    b.Property<int>("RegisteredServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RegisteredServerId");

                    b.HasIndex("SubscriptionId", "ResourceGroupName", "ServerName")
                        .IsUnique()
                        .HasDatabaseName("UQ_RegisteredServer_SubscriptionId_ResourceGroupName_ServerName");

                    b.ToTable("RegisteredServer", (string)null);
                });

            modelBuilder.Entity("SqlDbAnalyze.Repository.Entities.CachedDtuMetricEntity", b =>
                {
                    b.HasOne("SqlDbAnalyze.Repository.Entities.RegisteredServerEntity", "RegisteredServer")
                        .WithMany("CachedMetrics")
                        .HasForeignKey("RegisteredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredServer");
                });

            modelBuilder.Entity("SqlDbAnalyze.Repository.Entities.RegisteredServerEntity", b =>
                {
                    b.Navigation("CachedMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
